kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-trainee-role
  namespace: default
rules:
- apiGroups: [""] # indicates that core v1 api group
  resources: ["*"] # all objects pod, rs,dep.svc, ingress
  verbs: ["get","watch","list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-trainee-rb
  namespace: default
subjects:
- kind: User
  name: shubhashini
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: default-trainee-role
  apiGroup: rbac.authorization.k8s.io
