kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-trainee-role
  namespace: default
rules:
- apiGroups: [""] # indicates that core v1 api group
  resources: ["services"] # all objects pod, rs,dep.svc, ingress
  verbs: ["get", "watch", "list", "describe"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-trainee-rb
  namespace: default
subjects:
- kind: User
  name: shubhashini
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: default-trainee-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-trainee-cr
  namespace: default
rules:
- apiGroups: [""] #empty means core api group v1
  resources: ["*"] #all resources aceess allowed
  verbs: ["get","watch","list","describe"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-trainee-crb
  namespace: default
subjects:
- kind: User
  name: Shibhashini
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: default-trainee-cr
  apiGroup: rbac.authorization.k8s.io